//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Resources.Handlers.Subscriptions {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SubscriptionsHandler_uk_UA {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SubscriptionsHandler_uk_UA() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Application.Resources.Handlers.Subscriptions.SubscriptionsHandler_uk_UA", typeof(SubscriptionsHandler_uk_UA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ChooseSubscription {
            get {
                return ResourceManager.GetString("ChooseSubscription", resourceCulture);
            }
        }
        
        internal static string YourSubscriptions {
            get {
                return ResourceManager.GetString("YourSubscriptions", resourceCulture);
            }
        }
        
        internal static string YourSubscription {
            get {
                return ResourceManager.GetString("YourSubscription", resourceCulture);
            }
        }
        
        internal static string DoYouWantToCheckin {
            get {
                return ResourceManager.GetString("DoYouWantToCheckin", resourceCulture);
            }
        }
        
        internal static string ChooseSubscriptionPeriod {
            get {
                return ResourceManager.GetString("ChooseSubscriptionPeriod", resourceCulture);
            }
        }
        
        internal static string NoAvailableSubscriptions {
            get {
                return ResourceManager.GetString("NoAvailableSubscriptions", resourceCulture);
            }
        }
        
        internal static string BuySubscription {
            get {
                return ResourceManager.GetString("BuySubscription", resourceCulture);
            }
        }
        
        internal static string BuySubscriptionApproval {
            get {
                return ResourceManager.GetString("BuySubscriptionApproval", resourceCulture);
            }
        }
        
        internal static string NoSubscriptions {
            get {
                return ResourceManager.GetString("NoSubscriptions", resourceCulture);
            }
        }
        
        internal static string ChooseSubscriptionType {
            get {
                return ResourceManager.GetString("ChooseSubscriptionType", resourceCulture);
            }
        }
        
        internal static string SubscriptionClasses {
            get {
                return ResourceManager.GetString("SubscriptionClasses", resourceCulture);
            }
        }
        
        internal static string SubscriptionCourses {
            get {
                return ResourceManager.GetString("SubscriptionCourses", resourceCulture);
            }
        }
        
        internal static string BackToSubscriptions {
            get {
                return ResourceManager.GetString("BackToSubscriptions", resourceCulture);
            }
        }
    }
}
